# Alacritty themes
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux new-session -A -s $USER"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
dynamic_padding = true

[cursor]
style.blinking = "On"

[font]
size = 13.0
# https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
normal.family = "JetBrainsMono Nerd Font"
