general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.9

[cursor]
style.shape = "Underline"
style.blinking = "On"

[font]
size = 11.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
