# curl -LO --output-dir ~/.config/alacritty/themes https://github.com/catppuccin/alacritty/raw/main/catppuccin-mocha.toml
import = [ "~/.config/alacritty/themes/catppuccin-mocha.toml" ]

[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux new-session -A -s $USER"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9
dynamic_padding = true

[cursor]
style.blinking = "On"

[font]
size = 13.0
# https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip
normal.family = "JetBrainsMono Nerd Font"
