window:
  opacity: 0.95

font:
  size: 13.0
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  
cursor:
  unfocused_hollow: false
  style:
    shape: Underline
    blinking: On

env:
  TERM: xterm-256color

# Alacritty Theme
# https://github.com/alacritty/alacritty-theme
import:
  - ~/.config/alacritty/themes/themes/tokyo-night.yaml
